name: Deploy

on:
  push:
    branches:
      - ozelema-regianehenrique-projeto-intro-web-js

jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to labescola-regiane.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'labescola-regiane.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}